
-- KOPO_CUSTOMERDATA 테이블에서 CUSTOMERCODE를 12자리로 조회하고, 12자리가 아닐경우 앞에 *로 채우자

-- 일단 12자리로 만들자. LPAD를 이용하면 되겠다.

SELECT 
    LTRIM(LPAD(A.CUSTOMERCODE,12,'*'), '*') 
    FROM KOPO_CUSTOMERDATA A


SELECT * FROM KOPO_CUSTOMERDATA


-- 컬럼값 변경하기

SELECT 
    REPLACE('Male', 'female') as ALLMALE
    FROM KOPO_CUSTOMERDATA
    
    
SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT
    REPLACE('REGIONID', 'REGIONNUMBER')
    FROM KOPO_CUSTOMERDATA
    
    
SELECT * FROM KOPO_CUSTOMERDATA
-- 1. CUSTOMERDATA를 10자리로, 왼쪽에 0으로 채우기
-- 2. 고객코드의 뒷 4자리는 암호화루를 위해 *처리 하기
      -- 뒷 SUBSTR로 4자리의 인덱스를 뽑고 REPLACE 하자
      
      
--- REPLACE('AB','A','E') 'AB'에서 'A'를 'E'로      
SELECT REPLACE(LPAD(CUSTOMERCODE,10,0),SUBSTR(LPAD(CUSTOMERCODE,10,0),7,9), '****') FROM KOPO_CUSTOMERDATA

    


SELECT REPLACE(LPAD(CUSTOMERCODE,10,0), SUBSTR(LPAD(CUSTOMERCODE,10,0),7,9), '****') FROM KOPO_CUSTOMERDATA


--컬럼 값 합치기

SELECT * FROM KOPO_CUSTOMERDATA

SELECT CONCAT(STATENAME, ST) AS STATEDD FROM KOPO_CUSTOMERDATA

SELECT STATENAME||ST FROM KOPO_CUSTOMERDATA

SELECT
    CONCAT(ST,CONCAT('_',GENDER1)) AS PR
    FROM KOPO_CUSTOMERDATA


    
SELECT
    CONCAT(DOB,CONCAT('_',EMAIL)) AS PRD
    FROM KOPO_CUSTOMERDATA
    
    
    
SELECT * FROM NUMBER_EXAMPLE

SELECT
    ROUND(12.345,2) FROM DUAL

SELECT CEIL(12.345) FROM DUAL

SELECT FLOOR(12.345) FROM DUAL

SELECT MOD(12,10) FROM DUAL --나머지

SELECT POWER(3,2) FROM DUAL --제곱

SELECT * FROM NUMBER_EXAMPLE





-- 1. 변수화 전.
SELECT A.*,
   A.FIRST_NUMBER / A.SECOND_NUMBER AS AVG,
        ROUND(A.FIRST_NUMBER / A.SECOND_NUMBER,2) AS ROUND_EX,
            CEIL(A.FIRST_NUMBER / A.SECOND_NUMBER) AS CEIL_EX,
                FLOOR(A.FIRST_NUMBER / A.SECOND_NUMBER) AS FLOOR_EX,
                    MOD(A.FIRST_NUMBER, A.SECOND_NUMBER) AS MOD_EX,
                        POWER(A.FIRST_NUMBER, A.SECOND_NUMBER) AS POW_EX
FROM NUMBER_EXAMPLE A
   

--- 2. 변수화. SELECT 안에 SELECT로 테이블을 지정해준다.

SELECT B.*,
ROUND(B.AVG,2) AS ROUND_EX,
CEIL(B.AVG) AS CEIL_EX,
FLOOR(B.AVG) AS FLOOR_EX,
MOD(B.FIRST_NUMBER, B.SECOND_NUMBER) AS MOD_EX,
POWER(B.FIRST_NUMBER, B.SECOND_NUMBER) AS POW_EX
FROM 
(   
    SELECT A.*,
       A.FIRST_NUMBER / A.SECOND_NUMBER AS AVG
    FROM NUMBER_EXAMPLE A
) B


SELECT * FROM RMSE_MAE_EXAMPLE2
-- ACCRACY = 1 - ABS(예측값-실제값) / 예측값

-- 소숫점 반올림은 곱하고 반올림하면되는구나..
SELECT A.*,
    ROUND((1 - ABS(FCST - ACTUAL) / FCST)*100,2) AS ACCURACY
    FROM RMSE_MAE_EXAMPLE2 A
    
    
    
SELECT NEXT_DAY(SYSDATE,2) FROM DUAL

SELECT LAST_DAY(SYSDATE) FROM DUAL


SELECT * FROM RMSE_MAE_EXAMPLE2


SELECT A.*,
    CASE WHEN ITEM = 'ITEM0115' THEN 1000
END ITEEEE
FROM RMSE_MAE_EXAMPLE2 A




SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW



SELECT B.* FROM
( 
    SELECT 
        A.REGIONID,
        A.PRODUCT,
        A.YEARWEEK,
        A.QTY,
        CASE WHEN QTY<1000 THEN 1000
             WHEN QTY<10000 THEN 10000
             ELSE 30000 END AS QTY_NEW
    FROM KOPO_CHANNEL_SEASONALITY_NEW A
)B
WHERE 1=1
AND B.QTY >= 1000 
AND B.QTY < 10000
AND B.QTY_NEW !=10000 


    