

SELECT * --모든컬럼을 조회
FROM KOPO_PRODUCT_VOLUME2

SELECT    -- 테이블에A라는 별칭을 부여하고 A에있는 모든 컬럼을 조회해라
FROM KOPO_PRODUCT_VOLUME2 A

SELECT MAP_PRICE/IR AS PRO_PERCENT ,
A.*
FROM KOPO_PROMOTION A
WHERE 1=1
AND PLANWEEK > 201601

SELECT MAP_PRICE/IR AS PRO_PERCENT ,
A.REGIONID,..
A.ITEM
FROM KOPO_PROMOTION A
WHERE 1=1
AND PLANWEEK > 201601


ALT

SELECT A.REGIONID||'_'||A.PRODUCTGROUP||'_'||A.YEARWEEK AS PK,
A.*-- 테이블에A라는 별칭을 부여하고 A에있는 모든 컬럼을 조회해라
FROM KOPO_PRODUCT_VOLUME2 A


SELECT * FROM KOPO_PRODUCT_VOLUME2