SELECT * FROM KOPO_REGION_MST

SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW


SELECT A.*, B.REGIONNAME
FROM KOPO_CHANNEL_SEASONALITY_NEW A -- LEFT
LEFT JOIN KOPO_REGION_MST B -- RIGHT
ON A.REGIONID = B.REGIONID -- Å° ¼³Á¤



SELECT * FROM PRO_ACTUAL_SALES2

SELECT * FROM PRO_PROMOTION